CREATE TABLE "SYP"."MEALKIT_ANSWER_TEST" 
   (	"MEALKIT_ANSWER_NO" NUMBER(5,0), 
	"MEALKIT_ANSWER_QNA_NO" NUMBER(10,0), 
	"MEALKIT_ANSWER_TITLE" VARCHAR2(500 CHAR) COLLATE "USING_NLS_COMP", 
	"MEALKIT_ANSWER_TEXT" VARCHAR2(500 CHAR) COLLATE "USING_NLS_COMP", 
	"MEALKIT_ANSWER_DATE" DATE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

ALTER TABLE "SYP"."MEALKIT_ANSWER_TEST" MODIFY ("MEALKIT_ANSWER_QNA_NO" NOT NULL ENABLE);

ALTER TABLE "SYP"."MEALKIT_ANSWER_TEST" MODIFY ("MEALKIT_ANSWER_TITLE" NOT NULL ENABLE);

ALTER TABLE "SYP"."MEALKIT_ANSWER_TEST" MODIFY ("MEALKIT_ANSWER_TEXT" NOT NULL ENABLE);

ALTER TABLE "SYP"."MEALKIT_ANSWER_TEST" ADD PRIMARY KEY ("MEALKIT_ANSWER_NO")
  USING INDEX  ENABLE;
  
  ------------------------------------------
  CREATE TABLE "SYP"."MEALKIT_QNA_TEST" 
   (	"MEALKIT_QNA_NO" NUMBER(5,0), 
	"MEALKIT_QNA_MK_NO" NUMBER(10,0), 
	"MEALKIT_QNA_ID" VARCHAR2(500 CHAR) COLLATE "USING_NLS_COMP", 
	"MEALKIT_QNA_PW" NUMBER(10,0), 
	"MEALKIT_QNA_TITLE" VARCHAR2(500 CHAR) COLLATE "USING_NLS_COMP", 
	"MEALKIT_QNA_IMG" VARCHAR2(500 CHAR) COLLATE "USING_NLS_COMP", 
	"MEALKIT_QNA_TXT" VARCHAR2(500 CHAR) COLLATE "USING_NLS_COMP", 
	"MEALKIT_QNA_ANSWER_TITLE" VARCHAR2(500 CHAR) COLLATE "USING_NLS_COMP", 
	"MEALKIT_QNA_ANSWER_TXT" VARCHAR2(500 CHAR) COLLATE "USING_NLS_COMP", 
	"MEALKIT_QNA_ANSWER_CONFIRM" NUMBER(1,0), 
	"MEALKIT_QNA_DATE" DATE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

ALTER TABLE "SYP"."MEALKIT_QNA_TEST" MODIFY ("MEALKIT_QNA_MK_NO" NOT NULL ENABLE);

ALTER TABLE "SYP"."MEALKIT_QNA_TEST" MODIFY ("MEALKIT_QNA_ID" NOT NULL ENABLE);

ALTER TABLE "SYP"."MEALKIT_QNA_TEST" MODIFY ("MEALKIT_QNA_PW" NOT NULL ENABLE);

ALTER TABLE "SYP"."MEALKIT_QNA_TEST" MODIFY ("MEALKIT_QNA_TITLE" NOT NULL ENABLE);

ALTER TABLE "SYP"."MEALKIT_QNA_TEST" MODIFY ("MEALKIT_QNA_TXT" NOT NULL ENABLE);

ALTER TABLE "SYP"."MEALKIT_QNA_TEST" MODIFY ("MEALKIT_QNA_ANSWER_CONFIRM" NOT NULL ENABLE);

ALTER TABLE "SYP"."MEALKIT_QNA_TEST" ADD PRIMARY KEY ("MEALKIT_QNA_NO")
  USING INDEX  ENABLE;

  
  --------------------------------------------
  
  CREATE TABLE "SYP"."MEALKIT_REVIEW_TEST" 
   (	"MEALKIT_REVIEW_NO" NUMBER, 
	"MEALKIT_REVIEW_MK_NO" NUMBER, 
	"MEALKIT_REVIEW_TITLE" VARCHAR2(100 CHAR) COLLATE "USING_NLS_COMP", 
	"MEALKIT_REVIEW_IMG" VARCHAR2(500 CHAR) COLLATE "USING_NLS_COMP", 
	"MEALKIT_REVIEW_TXT" VARCHAR2(500 CHAR) COLLATE "USING_NLS_COMP", 
	"MEALKIT_REVIEW_STAR" NUMBER, 
	"MEALKIT_REVIEW_DATE" DATE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

ALTER TABLE "SYP"."MEALKIT_REVIEW_TEST" MODIFY ("MEALKIT_REVIEW_MK_NO" NOT NULL ENABLE);

ALTER TABLE "SYP"."MEALKIT_REVIEW_TEST" MODIFY ("MEALKIT_REVIEW_TITLE" NOT NULL ENABLE);

ALTER TABLE "SYP"."MEALKIT_REVIEW_TEST" MODIFY ("MEALKIT_REVIEW_IMG" NOT NULL ENABLE);

ALTER TABLE "SYP"."MEALKIT_REVIEW_TEST" MODIFY ("MEALKIT_REVIEW_TXT" NOT NULL ENABLE);

ALTER TABLE "SYP"."MEALKIT_REVIEW_TEST" ADD PRIMARY KEY ("MEALKIT_REVIEW_NO")
  USING INDEX  ENABLE;

------------------------------------------------------
  
  CREATE TABLE "SYP"."MEALKIT_TEST" 
   (	"MEALKIT_NO" NUMBER, 
	"MEALKIT_NAME" VARCHAR2(300 CHAR) COLLATE "USING_NLS_COMP", 
	"MEALKIT_PRICE" NUMBER, 
	"MEALKIT_TYPE" VARCHAR2(10 CHAR) COLLATE "USING_NLS_COMP", 
	"MEALKIT_IMG" VARCHAR2(500 CHAR) COLLATE "USING_NLS_COMP", 
	"MEALKIT_TXT" VARCHAR2(500 CHAR) COLLATE "USING_NLS_COMP", 
	"MEALKIT_DATE" DATE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

ALTER TABLE "SYP"."MEALKIT_TEST" MODIFY ("MEALKIT_NAME" NOT NULL ENABLE);

ALTER TABLE "SYP"."MEALKIT_TEST" MODIFY ("MEALKIT_PRICE" NOT NULL ENABLE);

ALTER TABLE "SYP"."MEALKIT_TEST" MODIFY ("MEALKIT_TYPE" NOT NULL ENABLE);

ALTER TABLE "SYP"."MEALKIT_TEST" MODIFY ("MEALKIT_IMG" NOT NULL ENABLE);

ALTER TABLE "SYP"."MEALKIT_TEST" MODIFY ("MEALKIT_TXT" NOT NULL ENABLE);

ALTER TABLE "SYP"."MEALKIT_TEST" ADD PRIMARY KEY ("MEALKIT_NO")
  USING INDEX  ENABLE;

